import { Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";

// Load Outfit as main font
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

// Load Geist Mono for monospace
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CoursePilot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${outfit.variable} ${geistMono.variable}`}>
        <body className="antialiased">
          <GoogleOneTap />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
